//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.05 at 09:22:43 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fpo.com/poc-spring-boot-soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fpo.poc_spring_boot_soap;
